spring:
  jpa:
    properties:
      hibernate:
        showSql: true
  application:
    name: catalog-api

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-marco.herokuapp.com/