spring:
  jpa:
    properties:
      hibernate:
        showSql: true
  application:
    name: catalog-api

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-marco.herokuapp.com/eureka/
  instance:
    hostname: eureka-server-marco.herokuapp.com
    nonSecurePort: 80